### PR TITLE
add sendgrid dependencies and store api key in sendgrid.env

### PR DESCRIPTION
**Pull request by torserver**
did i put these things in the right place?

### CODE REVIEW

**Review by palepinkdot — CHANGES_REQUESTED** [review]
Delete `sendgrid.env`. No need to introduce an new env file for one variable. Follow example set my the `.env` file and `.env.example`. For future reference, never push API keys to GitHub.

**Comment by torserver** [comment]
> Delete `sendgrid.env`. No need to introduce an new env file for one variable. Follow example set my the `.env` file and `.env.example`. For future reference, never push API keys to GitHub.

My bad I thought I put the .env file with api key in gitignore. My idea was to store the api key in that file which would be hidden from github and just reference later in the code so it would remain hidden. @palepinkdot

**Comment by torserver** [comment]
deleted old api key

**Review by torserver — COMMENTED** [review]
old api key removed and 'sendgrid.env' file renamed to 'env.sengrid'. Added to gitignore so API keys are not shared publicly

**Pull request closed without merging**
